import type {
  Alert,
  AuditEntry,
  ChainVerification,
  Dashboard,
  Decision,
  Environment,
  ExecutiveSummary,
  Incident,
  IncidentDetail,
  Indicator,
  Me,
  ResponseAction,
  Tokens,
} from "@/types/api";

export const MOCK_ADMIN: Me = {
  id: "usr_super_admin_01",
  email: "admin@threatplatform.dev",
  full_name: "Chief Security Officer",
  role: "super_admin",
  environment_id: null,
  is_active: true,
  mfa_enabled: false,
  permissions: [
    "alerts:read",
    "alerts:write",
    "audit:read",
    "audit:retention",
    "dashboard:read",
    "environments:read",
    "environments:write",
    "incidents:read",
    "incidents:write",
    "reports:read",
    "reports:write",
    "response:approve",
    "response:execute",
    "response:read",
    "review:decide",
    "review:read",
    "rules:read",
    "rules:write",
    "threat_intel:read",
    "threat_intel:write",
    "users:read",
    "users:write",
  ],
};

export const MOCK_ANALYST: Me = {
  id: "usr_analyst_01",
  email: "analyst@threatplatform.dev",
  full_name: "Lead SOC Analyst",
  role: "security_analyst",
  environment_id: "env_corp_01",
  is_active: true,
  mfa_enabled: false,
  permissions: [
    "alerts:read",
    "audit:read",
    "dashboard:read",
    "environments:read",
    "incidents:read",
    "incidents:write",
    "reports:read",
    "response:read",
    "review:decide",
    "review:read",
    "threat_intel:read",
    "threat_intel:write",
  ],
};

export const MOCK_TOKENS: Tokens = {
  access_token: "mock-soc-session-jwt-token-access",
  refresh_token: "mock-soc-session-jwt-token-refresh",
  token_type: "bearer",
  expires_in: 3600,
};

export const MOCK_ENVIRONMENTS: Environment[] = [
  {
    id: "env_aws_prod",
    name: "AWS Cloud Infrastructure (us-east-1)",
    type: "cloud",
    description: "Multi-AZ EKS clusters, VPC peering, and serverless lambdas",
    status: "healthy",
    is_active: true,
    authorized_sources: ["10.0.0.0/16", "cloudwatch", "guardduty"],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "env_corp_hq",
    name: "Corporate Enterprise HQ",
    type: "enterprise",
    description: "Active Directory, zero-trust gateway, endpoints & workstation pool",
    status: "warning",
    is_active: true,
    authorized_sources: ["172.16.0.0/12", "crowdstrike", "okta"],
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: "env_med_iot",
    name: "Medical Critical Device Grid",
    type: "hospital",
    description: "Isolated VLAN for telemetry sensors and telemetry stations",
    status: "critical",
    is_active: true,
    authorized_sources: ["192.168.100.0/24", "dicom_pacs"],
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: "env_univ_lab",
    name: "Academic Research Cluster",
    type: "college",
    description: "High-performance compute clusters and laboratory access terminals",
    status: "healthy",
    is_active: true,
    authorized_sources: ["10.200.0.0/16", "slurm_head"],
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
];

export const MOCK_DASHBOARD: Dashboard = {
  kpis: {
    total_events: 1842930,
    threats_detected: 94,
    threats_last_24h: 94,
    threats_trend_pct: -14.2,
    high_risk: 8,
    under_review: 5,
    blocked_contained: 23,
    open_incidents: 6,
  },
  threats_over_time: [
    { time: "00:00", high: 1, medium: 2, low: 5 },
    { time: "02:00", high: 0, medium: 1, low: 3 },
    { time: "04:00", high: 2, medium: 3, low: 4 },
    { time: "06:00", high: 1, medium: 2, low: 6 },
    { time: "08:00", high: 4, medium: 6, low: 11 },
    { time: "10:00", high: 7, medium: 12, low: 18 },
    { time: "12:00", high: 5, medium: 9, low: 15 },
    { time: "14:00", high: 8, medium: 14, low: 22 },
    { time: "16:00", high: 6, medium: 10, low: 17 },
    { time: "18:00", high: 3, medium: 7, low: 12 },
    { time: "20:00", high: 2, medium: 5, low: 8 },
    { time: "22:00", high: 4, medium: 4, low: 9 },
  ],
  severity_distribution: [
    { label: "critical", count: 8, percent: 9 },
    { label: "high", count: 26, percent: 28 },
    { label: "medium", count: 42, percent: 44 },
    { label: "low", count: 18, percent: 19 },
  ],
  top_sources: [
    { entity: "198.51.100.42 (Tor Exit Node)", count: 41, severity: "critical" },
    { entity: "203.0.113.19 (APT-29 / C2)", count: 28, severity: "high" },
    { entity: "10.0.4.12 (Compromised CI Runner)", count: 19, severity: "high" },
    { entity: "185.220.101.5 (Known Botnet)", count: 15, severity: "medium" },
    { entity: "usr_svc_backup (Service Account)", count: 11, severity: "medium" },
  ],
  environment_status: [
    {
      id: "env_aws_prod",
      name: "AWS Cloud Infrastructure",
      type: "cloud",
      status: "healthy",
      alerts_last_hour: 2,
      high_severity: 0,
    },
    {
      id: "env_corp_hq",
      name: "Corporate Enterprise HQ",
      type: "enterprise",
      status: "warning",
      alerts_last_hour: 7,
      high_severity: 2,
    },
    {
      id: "env_med_iot",
      name: "Medical Device Network",
      type: "hospital",
      status: "critical",
      alerts_last_hour: 12,
      high_severity: 5,
    },
    {
      id: "env_univ_lab",
      name: "Academic Research Cluster",
      type: "college",
      status: "healthy",
      alerts_last_hour: 1,
      high_severity: 0,
    },
  ],
};

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alt_001",
    rule_id: "AUTH-0001",
    title: "Brute Force SSH Attack Against Gateway Server",
    severity: "critical",
    environment_id: "env_corp_hq",
    entity: "198.51.100.42",
    event_ids: ["evt_101", "evt_102", "evt_103", "evt_104"],
    evidence: { failed_attempts: 142, target_service: "sshd", port: 22 },
    attack_tactic: "TA0006",
    attack_technique: "T1110.001",
    risk_score: 92,
    risk_factors: { impact: 4, likelihood: 5, asset_criticality: 4 },
    status: "active",
    incident_id: "inc_001",
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
  },
  {
    id: "alt_002",
    rule_id: "PRIV-0002",
    title: "Anomalous Sudo Privilege Escalation on Kubernetes Node",
    severity: "high",
    environment_id: "env_aws_prod",
    entity: "node-prod-worker-08",
    event_ids: ["evt_201", "evt_202"],
    evidence: { command: "sudo /bin/bash -p", user: "app_daemon" },
    attack_tactic: "TA0004",
    attack_technique: "T1548.003",
    risk_score: 84,
    risk_factors: { impact: 4, likelihood: 4, asset_criticality: 4 },
    status: "investigating",
    incident_id: "inc_002",
    created_at: new Date(Date.now() - 38 * 60000).toISOString(),
  },
  {
    id: "alt_003",
    rule_id: "EXFIL-0001",
    title: "Unusual Outbound Data Exfiltration to Anonymous Cloud Storage",
    severity: "critical",
    environment_id: "env_med_iot",
    entity: "pacs-archive-svr01",
    event_ids: ["evt_301", "evt_302", "evt_303"],
    evidence: { transferred_bytes: "4.8 GB", destination: "mega.nz / 142.250.72.14" },
    attack_tactic: "TA0010",
    attack_technique: "T1567",
    risk_score: 96,
    risk_factors: { impact: 5, likelihood: 5, asset_criticality: 5 },
    status: "active",
    incident_id: "inc_003",
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: "alt_004",
    rule_id: "NET-0003",
    title: "Rapid Port Sweep Across Internal Subnet",
    severity: "medium",
    environment_id: "env_corp_hq",
    entity: "172.16.40.118",
    event_ids: ["evt_401"],
    evidence: { scanned_ports: 1024, duration_sec: 4.2 },
    attack_tactic: "TA0007",
    attack_technique: "T1046",
    risk_score: 62,
    risk_factors: { impact: 2, likelihood: 4, asset_criticality: 3 },
    status: "active",
    incident_id: null,
    created_at: new Date(Date.now() - 85 * 60000).toISOString(),
  },
  {
    id: "alt_005",
    rule_id: "C2-0004",
    title: "Periodic Beaconing Pattern to Uncategorized Domain",
    severity: "high",
    environment_id: "env_univ_lab",
    entity: "hpc-gpu-node-03",
    event_ids: ["evt_501", "evt_502"],
    evidence: { domain: "dns-update-sync-service.cc", jitter_pct: 3.1 },
    attack_tactic: "TA0011",
    attack_technique: "T1071.001",
    risk_score: 79,
    risk_factors: { impact: 4, likelihood: 3, asset_criticality: 3 },
    status: "active",
    incident_id: null,
    created_at: new Date(Date.now() - 110 * 60000).toISOString(),
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc_001",
    reference: "INC-2026-0841",
    title: "Distributed SSH Credential Stuffing Campaign",
    description: "Sustained high-velocity brute force against perimeter jumpbox with rotating proxy IPs.",
    severity: "critical",
    risk_score: 92,
    risk_band: "CRITICAL",
    status: "in_review",
    environment_id: "env_corp_hq",
    alert_ids: ["alt_001"],
    assigned_to: "Chief Security Officer",
    attack_technique: "T1110.001 - Password Spraying",
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
    closed_at: null,
  },
  {
    id: "inc_002",
    reference: "INC-2026-0840",
    title: "Container Privilege Escalation & Host Escape Attempt",
    description: "App container invoked sudo with binary injection; potential kernel vulnerability probe.",
    severity: "high",
    risk_score: 84,
    risk_band: "HIGH",
    status: "investigating",
    environment_id: "env_aws_prod",
    alert_ids: ["alt_002"],
    assigned_to: "Lead SOC Analyst",
    attack_technique: "T1548.003 - Sudo Caching Abuse",
    created_at: new Date(Date.now() - 38 * 60000).toISOString(),
    closed_at: null,
  },
  {
    id: "inc_003",
    reference: "INC-2026-0839",
    title: "Large PACS Imaging Archive Data Exfiltration",
    description: "4.8 GB encrypted multipart archive transferred to unauthorized external cloud storage endpoint.",
    severity: "critical",
    risk_score: 96,
    risk_band: "CRITICAL",
    status: "decided",
    environment_id: "env_med_iot",
    alert_ids: ["alt_003"],
    assigned_to: "Chief Security Officer",
    attack_technique: "T1567 - Exfiltration Over Web Service",
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
    closed_at: null,
  },
  {
    id: "inc_004",
    reference: "INC-2026-0835",
    title: "Mimikatz LSASS Memory Dump Blocked on Domain Controller",
    description: "EDR intercepted LSASS memory handle request from unauthorized powershell process.",
    severity: "high",
    risk_score: 88,
    risk_band: "HIGH",
    status: "action_executed",
    environment_id: "env_corp_hq",
    alert_ids: [],
    assigned_to: "Lead SOC Analyst",
    attack_technique: "T1003.001 - LSASS Memory Dump",
    created_at: new Date(Date.now() - 180 * 60000).toISOString(),
    closed_at: null,
  },
  {
    id: "inc_005",
    reference: "INC-2026-0831",
    title: "Lateral Reconnaissance via SMB Named Pipes",
    description: "Scanned 42 internal hosts looking for open administrative shares and IPC$ access.",
    severity: "medium",
    risk_score: 68,
    risk_band: "MEDIUM",
    status: "closed",
    environment_id: "env_univ_lab",
    alert_ids: [],
    assigned_to: "Lead SOC Analyst",
    attack_technique: "T1021.002 - SMB/Windows Admin Shares",
    created_at: new Date(Date.now() - 360 * 60000).toISOString(),
    closed_at: new Date(Date.now() - 60 * 60000).toISOString(),
  },
];

export const MOCK_INCIDENT_DETAIL: IncidentDetail = {
  ...MOCK_INCIDENTS[0],
  evidence: [
    {
      id: "evi_01",
      kind: "network_capture",
      content: {
        protocol: "SSH-2.0-OpenSSH_8.9p1",
        failed_attempts_count: 142,
        user_list_probed: ["root", "admin", "deploy", "ubuntu", "test"],
        source_country: "Romania (Proxy Relay)",
      },
      content_hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      collected_by: "Ingestion Pipeline Worker 04",
      collected_at: new Date(Date.now() - 12 * 60000).toISOString(),
    },
    {
      id: "evi_02",
      kind: "ioc_enrichment",
      content: {
        ip: "198.51.100.42",
        abuseipdb_score: 100,
        virustotal_malicious: 28,
        threat_actor: "Storm-0501 / Automated Scanner Fleet",
      },
      content_hash: "a4f21b764c62d08a54d3d2a7c4f52b8813ef0467b93112c3f87b87ef248239ac",
      collected_by: "Threat Intel Engine",
      collected_at: new Date(Date.now() - 10 * 60000).toISOString(),
    },
  ],
  timeline: [
    {
      id: "tl_01",
      actor_id: "Detection Rule Engine",
      action: "ALERT_GENERATED",
      detail: "Rule AUTH-0001 threshold breached (142 failures in 5 minutes)",
      entry_metadata: { severity: "critical", score: 92 },
      created_at: new Date(Date.now() - 14 * 60000).toISOString(),
    },
    {
      id: "tl_02",
      actor_id: "Correlation Worker",
      action: "INCIDENT_PROMOTED",
      detail: "Automated promotion from high-severity alert to incident INC-2026-0841",
      entry_metadata: { confidence: 0.95 },
      created_at: new Date(Date.now() - 13 * 60000).toISOString(),
    },
    {
      id: "tl_03",
      actor_id: "Threat Intel Connector",
      action: "IOC_CORRELATED",
      detail: "IP 198.51.100.42 confirmed malicious on AbuseIPDB (100% confidence)",
      entry_metadata: { reports_count: 812 },
      created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    },
    {
      id: "tl_04",
      actor_id: "Chief Security Officer",
      action: "REVIEW_QUEUED",
      detail: "Containment decision staged: Pending operator authorization to block IP",
      entry_metadata: { target: "198.51.100.42", action: "block_ip" },
      created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    },
  ],
};

export const MOCK_INDICATORS: Indicator[] = [
  {
    id: "ioc_01",
    value: "198.51.100.42",
    type: "ip",
    source: "AbuseIPDB",
    confidence: 100,
    severity: "critical",
    description: "Known SSH scanner and credential stuffing relay",
    first_seen: new Date(Date.now() - 7 * 86400000).toISOString(),
    last_seen: new Date().toISOString(),
  },
  {
    id: "ioc_02",
    value: "203.0.113.19",
    type: "ip",
    source: "MISP Community Feed",
    confidence: 94,
    severity: "high",
    description: "C2 server associated with advanced persistent threat campaign",
    first_seen: new Date(Date.now() - 14 * 86400000).toISOString(),
    last_seen: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "ioc_03",
    value: "4e9d3000b953d5a41be745e69b5c3ff9d8ec3c0f4f91040854d6735e0767759b",
    type: "sha256",
    source: "AlienVault OTX",
    confidence: 98,
    severity: "critical",
    description: "BlackCat / ALPHV Ransomware encryptor binary",
    first_seen: new Date(Date.now() - 21 * 86400000).toISOString(),
    last_seen: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "ioc_04",
    value: "dns-update-sync-service.cc",
    type: "domain",
    source: "Internal Threat Intel",
    confidence: 88,
    severity: "high",
    description: "Fast-flux domain hosting dynamic DNS beacon targets",
    first_seen: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_seen: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const MOCK_DECISIONS: Decision[] = [
  {
    id: "dec_01",
    incident_id: "inc_001",
    analyst_id: "usr_super_admin_01",
    action: "block_contain",
    justification: "Critical SSH brute-force actively attacking gateway jumpbox. Containment required.",
    requires_approval: true,
    approved_by: null,
    approved_at: null,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "dec_02",
    incident_id: "inc_002",
    analyst_id: "usr_analyst_01",
    action: "block_contain",
    justification: "Isolate worker node 08 to prevent container escape across cluster.",
    requires_approval: true,
    approved_by: "usr_super_admin_01",
    approved_at: new Date(Date.now() - 15 * 60000).toISOString(),
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
];

export const MOCK_ACTIONS: ResponseAction[] = [
  {
    id: "act_01",
    incident_id: "inc_001",
    decision_id: "dec_01",
    action_type: "block_ip",
    target: "198.51.100.42",
    params: { duration_hours: 72, reason: "SSH Brute Force" },
    status: "pending_approval",
    dry_run: false,
    requested_by: "Chief Security Officer",
    approved_by: null,
    executed_by: null,
    result: {},
    rollback_token: "rb_tk_839218a",
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    executed_at: null,
  },
  {
    id: "act_02",
    incident_id: "inc_002",
    decision_id: "dec_02",
    action_type: "isolate_host",
    target: "node-prod-worker-08",
    params: { iptables_drop_all: true, allow_bastion_ssh: true },
    status: "executed",
    dry_run: false,
    requested_by: "Lead SOC Analyst",
    approved_by: "Chief Security Officer",
    executed_by: "Automated Response Dispatcher",
    result: { egress_blocked: true, iptables_rule_id: 8129 },
    rollback_token: "rb_tk_771239b",
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    executed_at: new Date(Date.now() - 14 * 60000).toISOString(),
  },
];

export const MOCK_AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: "aud_01",
    sequence: 1482,
    actor_id: "Chief Security Officer",
    action: "RESPONSE_ACTION_APPROVED",
    resource_type: "ResponseAction",
    resource_id: "act_02",
    details: { target: "node-prod-worker-08", action: "isolate_host" },
    entry_hash: "9b64c1b3f940bb2a7925e51d4512e09641e72e90e72fb4d3c9076fa7b12ec841",
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
  },
  {
    id: "aud_02",
    sequence: 1481,
    actor_id: "Lead SOC Analyst",
    action: "INCIDENT_STATUS_TRANSITION",
    resource_type: "Incident",
    resource_id: "inc_002",
    details: { from: "new", to: "investigating" },
    entry_hash: "2c7d9a18f4510b8e990c741e4892c0175b9f7123e445012398aef09b234199aa",
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: "aud_03",
    sequence: 1480,
    actor_id: "Automated Detection Pipeline",
    action: "INCIDENT_CREATED",
    resource_type: "Incident",
    resource_id: "inc_001",
    details: { title: "Distributed SSH Credential Stuffing Campaign", severity: "critical" },
    entry_hash: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    created_at: new Date(Date.now() - 38 * 60000).toISOString(),
  },
];

export const MOCK_CHAIN_VERIFICATION: ChainVerification = {
  valid: true,
  checked: 1482,
  broken_at: null,
  reason: null,
};

export const MOCK_SUMMARY: ExecutiveSummary = {
  generated_for: "Executive Board & CISO Operational Review",
  kpis: {
    total_events: 1842930,
    threats_detected: 94,
    high_risk: 8,
    open_incidents: 6,
    blocked_contained: 23,
    compliance_score: "99.4%",
    mean_time_to_detect: "48s",
    mean_time_to_respond: "3.4m",
  },
  note: "All monitored cloud and enterprise perimeters remain within compliant operational envelopes. Cryptographic SHA-256 ledger integrity verified 100% intact.",
};
